-- EXISTEM MUITAS FUNÇÕES, PODEMOS CONFERIR NA DOCUMENTAÇÃO E TAMBÉM NO W3 SCHOOL

SELECT LTRIM ('     OLÁ') AS RESULTADO;

SELECT RTRIM ('OLÁ     ') AS RESULTADO;

SELECT   TRIM('   OLÁ  ') AS RESULTADO;

SELECT CONCAT ('OLÁ',' ', 'TUDO BEM', '?') AS RESULTADO;

SELECT UPPER('olá, tudo bem?') AS RESULTADO;

SELECT substring('Missão em calabouço',10,10) AS RESULTADO;

SELECT CONCAT(NOME, '(',CPF,')') AS RESULTADO FROM TABELA_DE_CLIENTES;

SELECT NOME, CONCAT( ENDERECO_1,' ',BAIRRO,' ',CIDADE,' ',ESTADO) AS RESULTADO FROM TABELA_DE_CLIENTES;



